stages:
  XEntropyAugmented:
    cmd: "python3 -c \"from src.XEntropyAugmented import XEntropyAugmented; XEntropyAugmented.load(name='XEntropyAugmented').run_and_save()\"\
      \ "
    deps:
    - src/XEntropyAugmented.py
    metrics:
    - ./experiment/x-entropy_augmented_scores.json:
        cache: false
    outs:
    - ./experiment/x-entropy_augmented/ckpt_x-entropy_augmented.pt
  MaxEntropyL1:
    cmd: "python3 -c \"from src.MaxEntropyL1 import MaxEntropyL1; MaxEntropyL1.load(name='MaxEntropyL1').run_and_save()\"\
      \ "
    deps:
    - src/MaxEntropyL1.py
    outs:
    - experiment/max-entropy-L1_augmented/ckpt_max-entropy-L1_augmented.pt
    metrics:
    - experiment/max-entropy-L1_augmented_scores.json:
        cache: false
  MaxEntropyL2:
    cmd: "python3 -c \"from src.MaxEntropyL2 import MaxEntropyL2; MaxEntropyL2.load(name='MaxEntropyL2').run_and_save()\"\
      \ "
    deps:
    - src/MaxEntropyL2.py
    outs:
    - experiment/max-entropy-L2_augmented/ckpt_max-entropy-L2_augmented.pt
    metrics:
    - experiment/max-entropy-L2_augmented_scores.json:
        cache: false
  EvaluateX:
    cmd: "python3 -c \"from src.EvaluateX import EvaluateX; EvaluateX.load(name='EvaluateX').run_and_save()\"\
      \ "
    deps:
    - ./experiment/x-entropy_augmented/ckpt_x-entropy_augmented.pt
    - ./experiment/x-entropy_augmented_scores.json
    - experiment/max-entropy-L1_augmented/ckpt_max-entropy-L1_augmented.pt
    - experiment/max-entropy-L1_augmented_scores.json
    - experiment/max-entropy-L2_augmented/ckpt_max-entropy-L2_augmented.pt
    - experiment/max-entropy-L2_augmented_scores.json
    - src/EvaluateX.py
    plots:
    - ./experiment/max-entropy-L1_augmented_calibration.csv:
        cache: false
    - ./experiment/max-entropy-L2_augmented_calibration.csv:
        cache: false
    - ./experiment/x-entropy_augmented_calibration.csv:
        cache: false
